databases:
  hive:
    host: hadoop-master
  presto:
    host: presto-master
    configured_hdfs_user: hive
    cli_ldap_authentication: true
    cli_ldap_truststore_path: /etc/ldap/rootca/cacerts.jks
    cli_ldap_truststore_password: testldap
    cli_ldap_user_name: financeuser1
    cli_ldap_user_password: TCAMPass123
    cli_ldap_server_address: https://${databases.presto.host}:8443

  mysql:
    jdbc_driver_class: com.mysql.jdbc.Driver
    jdbc_url: jdbc:mysql://mysql:3306/test
    jdbc_user: root
    jdbc_password: swarm
    jdbc_pooling: true
    table_manager_type: jdbc

  postgres:
    jdbc_driver_class: org.postgresql.Driver
    jdbc_url: jdbc:postgresql://postgres:5432/test
    jdbc_user: swarm
    jdbc_password: swarm
    jdbc_pooling: true
    table_manager_type: jdbc
