databases:
  hive:
    host: hadoop-master
  presto:
    host: presto-master
    configured_hdfs_user: hive
  mysql:
    jdbc_url: jdbc:mysql://mysql:3306/test
  postgres:
    jdbc_url: jdbc:postgresql://postgres:5432/test
